import { cloneJsonValue } from '../../core/clone';
import type { FeaturedPluginConfig } from '../../types/config';
import { createSourceRule } from './configFactories';

export const CONFIG_DEFAULTS: FeaturedPluginConfig = {
  FrontendInjectionMethod: 'automatic',
  EnableFrontendBootstrap: true,
  SourceRules: [createSourceRule('RANDOM')],
  GlobalFilters: [],
  ManualLists: [],
  UserProfiles: [],
  PersonalizationDefaults: {
    UnplayedBoost: 25,
    FavouriteBoost: 20,
    PreferredGenreBoost: 15,
    InProgressSeriesBoost: 30,
    PreferredGenres: []
  },
  PersonalizationPolicy: {
    Enabled: true,
    AllowSourceSelection: false,
    AllowSourceWeights: false,
    AllowPreferredGenres: true,
    AllowUnplayedBoost: true,
    AllowFavouriteBoost: true,
    AllowInProgressSeriesBoost: true,
    AllowRepeatCooldown: false
  },
  DismissalPolicy: {
    Enabled: true,
    AllowTitle: true,
    AllowSeries: true,
    AllowFranchise: true
  },
  Presets: [],
  RepeatCooldownDays: 1,
  RelaxRepeatCooldownWhenNeeded: false,
  MaximumItemsPerGenre: 0,
  MaximumItemsPerFranchise: 0,
  RandomMediaCount: 5,
  EnableInfiniteLoading: false,
  MaximumParentRating: -2,
  MaximumParentRatingSubscore: 0,
  EnableAutoplay: true,
  ShowAutoplayButton: true,
  EnableBackgroundTrailers: false,
  TrailerSourcePriority: 'prefer_local',
  StartTrailersMuted: true,
  ShowTrailerControls: true,
  TrailerVolumeSliderDirection: 'down',
  HideYouTubeTrailerUntilControlsFade: true,
  WaitForTrailerToFinish: false,
  TrailerDelayMilliseconds: 1500,
  TrailerStartOffsetSeconds: 0,
  TrailerEndOffsetSeconds: 0,
  MultipleTrailerMode: 'first',
  AllowTrailersOnMobile: false,
  TrailerOverrides: [],
  AutoplayInterval: 10,
  ShowPlayButton: true,
  ShowFavoriteButton: true,
  FavoriteButtonPlacement: 'metadata',
  ShowPlaystateButton: true,
  PlaystateButtonPlacement: 'metadata',
  ShowDismissalButton: true,
  DismissalButtonPlacement: 'metadata',
  ShowNavigationArrows: true,
  BannerNavigationPosition: 'bottom-center',
  BannerMediaControlsPosition: 'top-right',
  ShowControlsOnHoverOnly: false,
  InteractOnWholeBanner: true,
  ShowSlidePosition: true,
  MediaPadding: 0,
  TitleDisplayMode: 'logo',
  ShowRating: true,
  ShowDescription: true,
  HideOnTvLayout: false,
  UseHeroLayout: true,
  HeroHeightMode: 'standard',
  TabletBannerHeight: 400,
  MobileBannerHeight: 340,
  HeroBorderRadius: 0,
  HeroGradientStrength: 100,
  HeroFadeStart: 50,
  HeroFadeEnd: 100,
  HeroFadeCurve: 'custom',
  HeroFadePoints: [
    { Position: 0, Fade: 0 },
    { Position: 30, Fade: 41 },
    { Position: 76, Fade: 67 },
    { Position: 100, Fade: 100 }
  ],
  HeroTextPosition: 'left',
  TransitionEffect: 'slide',
  HeroBackdropPosition: 'center',
  ReduceImageSize: false,
  EnablePreparedCache: true,
  BannerHeight: 360,
  ShowYear: true,
  ShowRuntime: true,
  ShowSecondaryButton: true,
  SecondaryButtonText: '',
  ShowPaginationDots: true,
  Heading: '',
  PlayButtonText: '',
  Debug: false
};

export function createDefaultConfig(): FeaturedPluginConfig {
  return cloneJsonValue(CONFIG_DEFAULTS);
}
